# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

#zeros:創建指定大小且數值都為0的矩陣。
#empty:不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。常見的數組內所有元素均為空，沒有實際意義，創建數組最快的方法。

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
import numpy as np

In [19]:
a = np.random.rand(2, 3)
a = a*100
print(np.round(a))

[[ 1. 26. 51.]
 [55.  1. 58.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [15]:
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m)
b = a

print((a - b % 1) + m)

SyntaxError: invalid character in identifier (<ipython-input-15-bedee2a4b80a>, line 5)